version: '3.3'

services:
  postgres:
    container_name: vacalendar_dev_postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "dev"
      POSTGRES_USER: "vacalendar"
      POSTGRES_PASSWORD: ""
    ports:
      - 5432:5432